version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: DockerFile

    networks:
      - webnet

    ports:
      - "80:80"

  db:
    image: postgres:16.2 
    restart: always
    shm_size: 128mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: appart
      POSTGRES_USER: postgres
    networks:
      - webnet
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    networks:
      - webnet
    ports:
      - "8080:8080"
networks:
  webnet:
